# -*- coding: utf-8 -*-
"""pytorch_fundamentals.DAY-1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19NPNF0RpB77u3yiYbkj8cpYB-j5mVxY5
"""

print("Hello I'm excited to learn PyTorch!")

import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

"""##Introduction to Tensor
###Creating tensors
"""

1 # scalar

scalar = torch.tensor(7)

scalar

scalar.ndim

# Get tensor back as Python int
scalar.item()

# Vector
vector =torch.tensor([7,7])
vector

vector.ndim

vector.shape

# MATRIX
MATRIX =torch.tensor([[7,8],
                     [9,10]])
MATRIX

MATRIX.ndim

MATRIX[1]

MATRIX.shape

# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                       [3,6,9],
                       [2,4,5]]])
TENSOR

TENSOR.ndim

TENSOR.shape

TENSOR[0]

# MY OWN EXAMPLE FOR TENSOR

TENSOR = torch.tensor([[[7,9,3],
                       [2,4,7],
                       [3,4,1]]])
TENSOR

TENSOR.ndim

TENSOR.shape

TENSOR[0]